Repository AbdiN7/utopiafrontend, pull requests merged in 2019-12, with the labels that each got.

#27 Added Redux actions for authenticating user
  package-lock.json
  package.json
  src/App.js
  src/actions/authActions.js
  src/actions/types.js
  src/components/appBarHeader.js
  src/components/auth/Login.js
  src/components/auth/Profile.js
  src/components/auth/Register.js
  src/index.js
  src/reducers/authReducer.js
  src/reducers/errorReducer.js
  src/reducers/index.js
  src/store.js
  src/util/setAuthToken.js
  src/validation/is-empty.js
Labels: Component, UI, enhancement

#28 User
  src/actions/authActions.js
  src/components/Payment.js
  src/components/SignUp.js
  src/components/UserForm.js
  src/components/auth/Login.js
  src/components/auth/Profile.js
  src/components/auth/Register.js
  src/components/home.js
  src/reducers/errorReducer.js
  src/store.js
Labels: UI

#44 User
  .babelrc
  package-lock.json
  package.json
  src/actions/authActions.js
  src/actions/types.js
  src/components/SignUp.js
  src/components/UserForm.js
  src/components/auth/Profile.js
  src/components/auth/Register.js
  src/reducers/authReducer.js
  src/store.js
Labels: UI, enhancement

#51 Find existing bookings
  src/App.js
  src/components/FindBookingForm.js
  src/components/TicketElement.js
  src/components/UserForm.js
  src/reducers/bookingReducer.js
Labels: Component, UI, enhancement

#52 Find existing bookings
  src/App.js
  src/components/CreateBookingForm.js
  src/components/FindBookingForm.js
  src/components/FlightListElement.js
  src/components/TicketListElement.js
  src/components/UserForm.js
Labels: UI, enhancement

#53 email is now checked before displaying the booking/tickets
  src/components/FindBookingForm.js
  src/components/FlightDate.js
  src/components/FlightList.js
  src/components/UserForm.js
Labels: enhancement

#55 Cancellation
  src/App.js
  src/actions/cancelActions.js
  src/actions/types.js
  src/components/BookingCancelListElement.js
  src/components/BookingList.js
  src/components/CancelForm.js
  src/components/TicketCancelListElement.js
  src/components/appBarHeader.js
  src/reducers/RootReducer.js
  src/reducers/cancelReducer.js
  src/styles/shared/_formButtons.scss
Labels: Component, UI, enhancement
