Repository AbdiN7/utopiafrontend, pull requests merged in 2019-11, with the labels that each got.

#5 Made changes to Webpack
  .gitignore
  package-lock.json
  package.json
  src/App.js
  src/components/FlightClass.js
  src/components/FlightDate.js
  src/components/FlightList.js
  src/components/PathForm.js
  src/components/appBarHeader.js
  src/static/fonts/Roboto-Bold.ttf
  src/static/fonts/Roboto-Italic.ttf
  src/static/fonts/Roboto-Light.ttf
  src/static/fonts/Roboto-Regular.ttf
  src/styles/_appbar.scss
  src/styles/app.scss
  src/styles/shared/_fonts.scss
  webpack.config.js
Labels: enhancement

#6 Components
  package-lock.json
  package.json
  src/App.js
  src/components/appBarHeader.js
  src/static/fonts/Roboto-Bold.ttf
  src/static/fonts/Roboto-Italic.ttf
  src/static/fonts/Roboto-Light.ttf
  src/static/fonts/Roboto-Regular.ttf
  src/styles/_appbar.scss
  src/styles/app.scss
  src/styles/shared/_fonts.scss
  webpack.config.js
Labels: enhancement

#7 added signup page temp default template
  package-lock.json
  package.json
  src/App.js
  src/components/SignUp.js
Labels: enhancement

#9 Components
  .babelrc
  package-lock.json
  package.json
  src/App.js
  src/components/BookingList.js
  src/components/FlightClass.js
  src/components/FlightDate.js
  src/components/PathForm.js
  src/components/SignUp.js
  src/components/UserForm.js
  src/components/appBarHeader.js
  src/components/home.js
  src/index.js
  src/serviceWorker.js
  src/static/images/UtopiaAir.jpg
  src/styles/_home.scss
  src/styles/app.scss
  webpack.config.js
Labels: Config, UI

#20 prev/next btns no longer move around
  src/components/FlightDate.js
  src/components/PathForm.js
  src/components/QueriedTicketList.js
Labels: Optimization, UI
